my_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

my_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

my_cats/app/models/cat.rb
require 'action_view'
class Cat <ApplicationRecord 
    include ActionView::Helpers::DateHelper
     
    validates :birth_date, :color, :name, :sex, presence: true

    validates :color, inclusion: { in: %w(orange black white grey) }

    validates :sex, inclusion: { in: %w(F M) }

    def age
        time_ago_in_words(birth_date)
    end

    

end

my_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

my_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController


    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        render :show
    end

    def new
        @cat=Cat.new
        render :new
    end


end

my_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

my_cats/app/views/cats/_cat.html.erb
<table>

    <tbody>
    <tr>  <td>Attribute</td>  <td>Value</td>  </tr>
    <tr> <td>name:</td> <td><%= cat.name %></td> </tr>
    <tr> <td>birth date:</td> <td><%= cat.birth_date %></td> </tr>
    <tr> <td>age:</td> <td> <%= cat.age %></td> </tr>
    <tr> <td>color:</td> <td><%= cat.color %>  </td> </tr>
    <tr> <td>sex:</td> <td><%= cat.sex %> </td> </tr>
    <tr> <td>description:</td> <td><%= cat.description %></td> </tr>

    </tbody>

</table>

my_cats/app/views/cats/index.html.erb
<ul>
    <% @cats.each do |cat| %>
        <li> 
        <a href="<%= cat_url(cat) %>"> <%= cat.name %></a>
        
        </li>
        <br> 
    <% end %>
</ul>

my_cats/app/views/cats/new.html.erb
<form action= "<%= cats_url %>" method="post">
<label for="cat_name" >name: </label>
<input type="text" id="cat_name" name="cat[name]" value="<%= @cat.name %>">
<br>

<label for="cat_sex">sex: </label>
<input type="radio" id="cat_male" name="cat[sex]"  value="M">
<label for="cat_male"> M</label>
<input type="radio" id="cat_female" name="cat[sex]"  value="F">
<label for="cat_female"> F</label>

<br>
<label for="cat_color"> color:</label>
<select name="options" id="cat_color">
     <option value="orange">orange</option>
     <option value="black">black</option>
     <option value="white">white</option>
     <option value="grey">grey</option>    
</select>

<br>
<label for="birth_date">birth date:</label>
<input type="birth_date" id="birth_date" name="cat[birth]">





</form>

my_cats/app/views/cats/show.html.erb
<%= render 'cat', cat: @cat %>

<a href="<%= cats_url %>">Back to the main page</a>

my_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>